## name: noirblaze
## author: Dimitar Dimitrov (https://github.com/n1ghtmare)


#: The basic colors

foreground                      #d5d5d5
background                      #121212
selection_foreground            #d5d5d5
selection_background            #444444


#: Cursor colors

cursor              #ff2222
cursor_text_color   background


#: URL underline color when hovering with mouse

url_color           #004444

#: kitty window border colors and terminal bell colors

active_border_color     #ff2222
inactive_border_color   #000000
bell_border_color       #ff2222


#: Tab bar colors

active_tab_foreground   #ffffff
active_tab_background   #000000
inactive_tab_foreground #ffffff
inactive_tab_background #000000


#: The basic 16 colors

#: black
color0 #000000
color8 #737373

#: red
color1 #ff2222
color9 #ff2222

#: green
color2  #44bbbb
color10 #ff2222

#: yellow
color3  #ffffff
color11 #ffffff

#: blue
color4  #006666
color12 #22ffff

#: magenta
color5  #7a7a7a
color13 #939393

#: cyan
color6  #44bbbb
color14 #44bbbb

#: white
color7  #d5d5d5
color15 #f5f5f5


#: Colors for marks (marked text in the terminal)

mark1_foreground #121212
mark1_background #787878

mark2_foreground #121212
mark2_background #7a7a7a

mark3_foreground #121212
mark3_background #ffffff
