# yazi.toml
[manager]
show_hidden = true

[opener]
play = [
	{ run = 'mpv "$@"', orphan = true, for = "unix" },
]
edit = [
	{ run = '"neovide" "$@"', orphan=true, block = true, for = "unix" },
]
open = [
	{ run = 'xdg-open "$@"', desc = "Open" },
]
pdf-viewer = [
	{ run = 'zathura "$@"', orphan = true, desc = "Zathura", for = "unix" },
]

[open]
prepend_rules = [
    { mime = "application/pdf", use = [ "pdf-viewer" ] },
    { url = "*.pdf", use = "pdf-viewer" },
	{ url = "*.json", use = "edit" },
	{ url = "*.sh", use = "edit" },
	{ url = "*.toml", use = "edit" },
	{ url = "*.y*ml", use = "edit" },
	{ url = "*config", use = "edit" },
	{ url = "*.cfg", use = "edit" },
	{ url = "*env", use = "edit" },
	{ url = "*.d", use = "edit" },
	{ url = "*.md", use = "edit" },
	{ url = "*.txt", use = "edit" },
	{ url = ".zsh*", use = "edit" },
	{ url = "*.ini", use = "edit" },
	{ url = "*.lua", use = "edit" },
	{ url = "*.xml", use = "edit" },
	{ url = "*.log", use = "edit" },
# open with normal / gnome / kde
	{ url = "*.ods", use = "open" },
# open with multimedia player
	{ url = "*.mp3", use = "play" },

]
append_rules = [
	{ url = "*", use = "edit" },
]
